=== Luis-Rivas/xmlvalido_grupo4/Ejercicios/dtd_externa/listaCompras.dtd
<!ELEMENT root (a,lista+)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a  
  href CDATA #IMPLIED
  xmlns CDATA #IMPLIED 
  target (_blank|_self|marco) "_blank">
<!ELEMENT lista (categoria+)>
<!ATTLIST lista propietario CDATA #IMPLIED>
<!ELEMENT categoria (producto*)>
<!ATTLIST categoria nombre CDATA #REQUIRED>
<!ELEMENT producto (nombre,precio,cantidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>

=== Luis-Rivas/xmlvalido_grupo4/Ejercicios/dtd_externa/listaCompras.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE root SYSTEM "listaCompras.dtd">
<root>
<a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" target="marco">Volver al inicio</a>
<lista>
<categoria nombre="Comida">
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
</categoria>
<categoria nombre="Salud">
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
</categoria>
<categoria nombre="Cuidado Personal">
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
</categoria>
<categoria nombre="Limpieza">
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
<producto>
<nombre>Pollo</nombre>
<precio>1.50</precio>
<cantidad>1lb</cantidad>
</producto>
</categoria>
</lista>
</root>
